language: python

script:
    - pip install .

after_success:
    - civic-api-client variants-list --no-coords

os:
    - linux

notifications:
    email:
        on_failure: always
        on_success: change
