language: python

script:
    - pip install .

after_success:
    - civic-api-client variants-list --no-coords
    - civic-api-client variants-list --max-gene-count=100 --no-variant-types

os:
    - linux

notifications:
    email:
        on_failure: always
        on_success: change
